### ISSUE TITLE
Error On Load

### ISSUE THREAD

**Issue by ZandercraftGames** [PetteriM1/VersionExtension#1]
The plugin throws the following error when loading:
```
23:31:21 [INFO ] Enabling VersionExtension v1.0
> java.lang.NoSuchFieldException: modifiers
        at java.base/java.lang.Class.getDeclaredField(Class.java:2489)
        at me.petterim1.versionextension.Main.onEnable(Main.java:26)
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:99)
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:118
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:462)
        at cn.nukkit.Server.enablePlugin(Server.java:922)
        at cn.nukkit.Server.enablePlugins(Server.java:911)
        at cn.nukkit.Server.<init>(Server.java:754)
        at cn.nukkit.Nukkit.main(Nukkit.java:120)
```

**Comment by PetteriM1** [comment]
Your server is running on a Java version newer than 11, right?

**Comment by ZandercraftGames** [comment]
@PetteriM1 That is correct, version 14 to be precise.

**Comment by PetteriM1** [comment]
> @PetteriM1 That is correct, version 14 to be precise.

Ok that is not supported
